[package]
name    = "wimlib"
version = "0.2.0"
edition = "2021"

description = "(Hopefully) idomatic bindings to the wimlib library"
repository  = "https://codeberg.org/erin/toolsnt"
license     = "EUPL-1.2"
categories  = ["api-bindings"]
keywords    = [
	"windows",
	"wim",
	"esd",
	"installation"
]

[features]
default = ["mount", "wimlib-sys/bundled"]
mount   = []

[dependencies]
wimlib-sys = { path = "./sys", version = "0.2" }

beef        = "0.5"
bitflags    = "2.5"
cfg-if      = "1.0"
delegate    = "0.12"
derive_more = "0.99"
paste       = "1.0"
uuid        = "1.8"
widestring  = "1.1"

[dependencies.time]
version  = "0.3"
features = ["macros"]

[target.'cfg(windows)'.dependencies.windows]
version  = "0.58"
features = ["Win32_Security"]
