[package]
name    = "wimlib"
version = "0.3.1"
edition = "2021"

description = "(Hopefully) idomatic bindings to the wimlib library"
repository  = "https://codeberg.org/erin/toolsnt"
license     = "EUPL-1.2"
categories  = ["api-bindings"]
keywords    = [
	"windows",
	"wim",
	"esd",
	"installation"
]

[features]
default = ["mount", "ntfs-3g"]
bundled = ["wimlib-sys/bundled"]
ntfs-3g = ["wimlib-sys/sys-ntfs-3g"]
mount   = []

[dependencies]
wimlib-sys = { path = "./sys", version = "0.3" }

beef        = "0.5"
bitflags    = "2"
cfg-if      = "1"
delegate    = "0.13"
paste       = "1"
uuid        = "1"
widestring  = "1"

[dependencies.derive_more]
version  = "2"
features = ["deref", "deref_mut", "display", "error"]

[dependencies.time]
version  = "0.3"
features = ["macros"]

[target.'cfg(windows)'.dependencies.windows]
version  = "0.58"
features = ["Win32_Security"]
