[package]
name    = "hivex-sys"
version = "0.1.0"
edition = "2021"
links   = "hivex"

description = "Raw and generated bindings to Hivex"
repository  = "https://codeberg.org/erin/toolsnt"
categories  = ["external-ffi-bindings"]
license     = "EUPL-1.2"

[build-dependencies]
bindgen    = "0.70"
pkg-config = "0.3"
