[package]
name    = "hivex-sys"
version = "0.2.1"
edition = "2021"
links   = "hivex"

description = "Raw and generated bindings to Hivex"
repository  = "https://codeberg.org/erin/toolsnt"
categories  = ["external-ffi-bindings"]
license     = "EUPL-1.2"

[features]
bundled = []

[build-dependencies]
autotools  = { workspace = true }
bindgen    = { workspace = true }
const-str  = { workspace = true }
flate2     = { workspace = true }
pkg-config = { workspace = true }
sha2       = { workspace = true }
tar        = { workspace = true }
