[package]
name    = "hivex-sys"
version = "0.2.1"
edition = "2021"
links   = "hivex"

description = "Raw and generated bindings to Hivex"
repository  = "https://codeberg.org/erin/toolsnt"
categories  = ["external-ffi-bindings"]
license     = "EUPL-1.2"

[features]
bundled = []

[build-dependencies]
autotools  = "0.2"
bindgen    = "0.71"
const-str  = "0.6"
flate2     = "1"
pkg-config = "0.3"
sha2       = "0.10"
tar        = "0.4"
