[package]
name    = "bcdedit-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bcdedit"
path = "src/main.rs"

[dependencies]
bcdedit.path = ".."
hivex.path   = "../../hivex"

clap        = { version = "4.5", features = ["derive"] }
error-stack = "0.5"
owo-colors  = "4.1"
uuid        = "1.11"
tabled      = "0.16"

[dependencies.derive_more]
version  = "1.0"
features = ["display", "error"]
