[package]
name    = "hivex"
version = "0.2.0"
edition = "2021"

description = "(Hopefully) idiomatic bindings to the Hivex library"
repository  = "https://codeberg.org/erin/toolsnt"
license     = "EUPL-1.2"
categories  = ["api-bindings"]
keywords    = [
	"windows-registry",
	"hive",
	"registry",
	"bindings",
	"windows"
]

[features]
bundled = ["hivex-sys/bundled"]

[dependencies]
hivex-sys = { path = "sys", version = "0.2" }

allocator-api2 = "0.3"
bitflags       = "2"
libc_alloc     = "1"
time           = { version = "0.3", features = ["macros"] }

[dev-dependencies.uuid]
version  = "1"
features = ["v4", "fast-rng"]
